# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('given', models.TextField()),
                ('prove', models.TextField()),
                ('diagram', models.FileField(upload_to='')),
                ('plan', models.TextField()),
                ('statements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('reasons', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
