# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0002_auto_20160720_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axioms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField()),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proof.Proof')),
            ],
        ),
    ]
