# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0003_axioms_definition_theorem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Axioms',
            new_name='Axiom',
        ),
    ]
