# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0004_auto_20160721_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theorem',
            name='proof',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='term',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='proof',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='axiom',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proof',
            name='statement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Theorem',
        ),
    ]
