# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0006_auto_20160721_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('AX', 'Axiom'), ('DE', 'Definition'), ('TH', 'Theorem')], default=None, max_length=2, null=True)),
                ('name', models.TextField()),
                ('statement', models.TextField()),
            ],
        ),
    ]
