# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0007_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement',
            field=models.CharField(max_length=255),
        ),
    ]
