# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 15:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proof', '0008_auto_20160722_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.CharField(max_length=255)),
                ('prove', models.CharField(max_length=255)),
                ('diagram', models.FileField(null=True, upload_to='')),
                ('note', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('statements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proof.Statement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='theorem',
            name='diagram',
            field=models.FileField(null=True, upload_to='/Users/openstax/workspace/Math-Proof-REST-API/media'),
        ),
    ]
