# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 15:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0010_auto_20160722_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='citation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='argument',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='argument',
            name='statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
