# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0014_statement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='label',
            field=models.CharField(choices=[('AX', 'Axiom'), ('DE', 'Definition'), ('TH', 'Theorem'), ('LE', 'Lemma'), ('CO', 'Corollary')], default=None, max_length=2, null=True),
        ),
    ]
