# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0017_auto_20160722_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definitions', models.FileField(upload_to='/Users/openstax/workspace/Math-Proof-REST-API/data/media')),
                ('axioms', models.FileField(upload_to='/Users/openstax/workspace/Math-Proof-REST-API/data/media')),
                ('theorems', models.FileField(upload_to='/Users/openstax/workspace/Math-Proof-REST-API/data/media')),
                ('proofs', models.FileField(null=True, upload_to='/Users/openstax/workspace/Math-Proof-REST-API/data/media')),
                ('citation', models.FileField(upload_to='/Users/openstax/workspace/Math-Proof-REST-API/data/media')),
            ],
        ),
    ]
